services:
  db:
    container_name: postgres
    image: postgres:17-alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
